log_dir: Log/EncoderDecoder/ED_SingleValue/
data:
  data_file: RawData/Kontum-daily.csv
  split_point: 0.15
  norm_method: std
  cols_x:
    - 3
    - 4
    - 5
    - 6
    - 7
  cols_y:
    - 5
  target_name: q
  target_timestep: 5
model:
  window_size: 5
  batch_size: 128
  epochs: 350
  input_dim: 5
  output_dim: 1
  patience: 20
  dropout: 0
  lr_decay: 0.000001
