log_dir: Log/EncoderDecoder/
data:
  data_file: RawData/Kontum-daily.csv
  split_point: 0.15
  norm_method: min_max
  cols_x:
    - 3
    - 4
    - 7
    - 6
    - 5
  cols_y:
    - 5
    - 7
  target_timestep: 1
model:
  window_size: 2
  batch_size: 128
  epochs: 300
  input_dim: 5
  output_dim: 2
  patience: 50
  dropout: 0
  lr_decay: 0.000001
