log_dir: Log/EncoderDecoder/
data:
  data_file: RawData/Hanoi/SonTay.csv
  split_point: 0.15
  norm_method: min_max
  cols_x:
    - 0
    - 1
    - 2
    - 3
    - 4
  cols_y:
    - 3
    - 2
  target_timestep: 1
model:
  window_size: 5
  batch_size: 128
  epochs: 500
  input_dim: 5
  output_dim: 2
  patience: 50
  dropout: 0
  lr_decay: 0.000001
