log_dir: Log/Ensemble/
data:
  data_file: RawData/Hanoi/Merge_HN.csv
  split_point_outer: 0.06
  split_point_inner: 0.45
  norm_method: min_max
  cols_x:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 16
    - 17
    - 18
  cols_y:
    - 17
    - 3
  window_size: 5
  target_timestep: 1
model:
  epoch_min: 100
  epoch_max: 250
  epoch_step: 50
  epochs_out: 400
  in_dim: 8
  out_dim: 2
  patience: 50
  batch_size: 128
  dropout: 0
